In [2]:
import numpy as np

In [3]:
#Concanate to numpy
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b

array([5, 6, 7, 8, 9])

In [6]:
a + b

array([ 6,  8, 10, 12, 14])

In [8]:
x = np.concatenate([a,b])

In [9]:
x

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [10]:
l =[10,11]

In [11]:
x = np.concatenate([a,b,l])

In [15]:
x

array([ 1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10, 11, 10, 11])

In [16]:
x = np.concatenate([a,b])

In [17]:
l = [12,14,"ali"]

In [18]:
x = np.concatenate([a,b,l])

In [19]:
x

array(['1', '2', '3', '4', '5', '5', '6', '7', '8', '9', '12', '14',
       'ali'], dtype='<U11')

In [21]:
x = np.array([[1,2,3],[4,5,6]])

In [22]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
x.size

6

In [24]:
x.ndim

2