In [1]:
#Conditional Index
import numpy as np

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
a[a<5]

array([1, 2, 3, 4])

In [6]:
filt = a < 5

In [7]:
filt

array([ True,  True,  True,  True, False, False, False, False, False])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[filt]

array([1, 2, 3, 4])

In [10]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [11]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [12]:
a[a==b]

array([3, 4, 5, 7, 8])

In [13]:
b[a==b]

array([3, 4, 5, 7, 8])

In [14]:
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [15]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [17]:
a == 8

array([False, False, False, False, False, False, False,  True, False])

In [18]:
a[a==6]

array([6])

In [19]:
a < 2 and a > 4 # or and mantıkları burada kullanılamaz  or -> | and -> &

<class 'ValueError'>: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
( a > 3) | (a < 5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
# not kullanmak için ise ~ (tilda) kullanılmaktadır