In [1]:
#Sortking
import numpy as np

In [2]:
a = np.array([20,32,5,30,10])

In [3]:
a

array([20, 32,  5, 30, 10])

In [4]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [5]:
a.sort()

In [6]:
a # a yı günceller a = np.sort(a) ile aynı durumdur.

array([ 5, 10, 20, 30, 32])

In [9]:
a = np.array([3,1,6,5,4,2])
b = np.argsort(a) # küçükten büyüğe sıralamaktadır. Ancak bize eski halindekini referans alarak indexlerini döndürmektedir.

In [11]:
b

array([1, 5, 0, 4, 3, 2], dtype=int32)

In [15]:
# Min Max
my_array = np.array([[2, 5],[3, 7],
                        [1, 3],
                        [4, 0]])

In [16]:
my_array

array([[2, 5],
       [3, 7],
       [1, 3],
       [4, 0]])

In [24]:
a = np.min(my_array,axis = 0) # sırasıyla bütün sütünları dolaşarak en küçük değerleri almaktadır.

In [25]:
a

array([1, 0])

In [27]:
b = np.min(my_array,axis = 1) # sırasıyla bütün satırları dolaşarak en küçük değerleri almaktadır.

In [28]:
b

array([2, 3, 1, 0])

In [29]:
x = np.max(my_array,axis = 0)# sırasıyla bütün sütünları dolaşarak en büyük değerleri almaktadır.

In [30]:
x

array([4, 7])

In [31]:
y = np.max(my_array,axis = 1)# sırasıyla bütün sütünları dolaşarak en büyük değerleri almaktadır.

In [32]:
y

array([5, 7, 3, 4])

In [33]:
#Fancy Indexing
x =np.arange(1,15)

In [34]:
idxs =[4,5,7,11]

In [35]:
x[idxs]

array([ 5,  6,  8, 12])

In [36]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
a = np.arange(12).reshape(3,4)

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a[0:2,1] # 0 ve 1 arrayi al ve bunların 1. sütünunu al 

array([1, 5])

In [42]:
a[0:2,1].shape  # Bu bir sayı öbeğidir. 

(2,)

In [43]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [44]:
a[0:2,1:3].shape

(2, 2)

In [45]:
a[0,[1,3]] # 0. satırdaki 1 ve 3 sütündaki değerleri döndür

array([1, 3])

In [46]:
a[0:,[1,3]] # Bütün satırlar tara ve 1 ve 3 sütündaki değerleri al

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [47]:
idex = [1,3,2]

In [48]:
idex1 = [3,0,2]

In [50]:
a = np.arange(20).reshape(4,5)

In [51]:
a[idex,idex1]

array([ 8, 15, 12])

In [52]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
a[idex,idex1].shape

(3,)

In [54]:
a[idex][idex1]

<class 'IndexError'>: index 3 is out of bounds for axis 0 with size 3

In [55]:
a[1,2,3] = 20

<class 'IndexError'>: too many indices for array: array is 2-dimensional, but 3 were indexed

In [56]:
a[1,2] = 20 # 1. satır 2. sütünu 20 yaptık

In [57]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 20,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
a[[0,1,3]] # 0,1,3 satırları aldık

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 20,  8,  9],
       [15, 16, 17, 18, 19]])

In [61]:
a[[0,1,3]] = 20  0,1,3 # satırdaki tüm elemanları sıfır yaptık

In [62]:
a

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [10, 11, 12, 13, 14],
       [20, 20, 20, 20, 20]])