In [1]:
import numpy as np

In [2]:
a = np.arange(1,11)

In [3]:
a.ndim

1

In [4]:
a.size

10

In [5]:
a.reshape(2,5)  # a nın eleman sayısı 10 olduğu için yapılacak reshape eleman sayısıda 10 olamsı gerekmektedir

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
a.reshape(6,2)

<class 'ValueError'>: cannot reshape array of size 10 into shape (6,2)

In [8]:
a.reshape(-1,2)  # -1 burada 5 olarak görülmektedir 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
a.reshape(2,-1) # -1 burada 2 olarak görülmektedir 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])