In [1]:
import numpy as np

In [2]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.zeros([3,8,8,5])

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



In [9]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.random.randint(1,10,(3,4))

array([[3, 8, 1, 2],
       [4, 5, 7, 9],
       [4, 3, 2, 2]])

In [11]:
np.random.randint(1,10,(3,5,5))

array([[[9, 7, 2, 3, 1],
        [1, 3, 4, 9, 6],
        [9, 3, 3, 4, 8],
        [2, 2, 5, 3, 7],
        [2, 5, 8, 6, 4]],

       [[6, 7, 5, 3, 4],
        [1, 5, 7, 3, 3],
        [3, 4, 3, 2, 9],
        [3, 5, 5, 1, 6],
        [2, 4, 7, 3, 2]],

       [[8, 6, 9, 1, 1],
        [1, 6, 5, 3, 5],
        [7, 3, 4, 1, 2],
        [9, 3, 2, 9, 8],
        [6, 3, 6, 9, 8]]])

In [12]:
np.random.randint(1,10,(3,3,5,5))

array([[[[9, 5, 2, 8, 1],
         [3, 6, 4, 9, 2],
         [6, 1, 1, 4, 7],
         [7, 5, 8, 9, 8],
         [5, 8, 9, 7, 8]],

        [[2, 1, 9, 4, 7],
         [1, 8, 3, 5, 8],
         [9, 1, 2, 7, 5],
         [4, 7, 3, 8, 4],
         [1, 2, 1, 3, 7]],

        [[2, 7, 9, 6, 2],
         [5, 7, 8, 3, 3],
         [5, 1, 7, 2, 6],
         [5, 2, 4, 2, 6],
         [1, 6, 5, 3, 6]]],


       [[[1, 9, 6, 4, 5],
         [4, 8, 5, 8, 5],
         [9, 6, 5, 4, 4],
         [3, 2, 1, 1, 4],
         [9, 4, 1, 9, 6]],

        [[2, 5, 6, 8, 2],
         [8, 9, 4, 2, 3],
         [1, 5, 9, 2, 9],
         [1, 2, 4, 9, 8],
         [7, 9, 2, 5, 3]],

        [[5, 8, 4, 3, 6],
         [5, 4, 1, 6, 4],
         [3, 6, 5, 5, 9],
         [3, 5, 7, 9, 8],
         [3, 5, 2, 3, 1]]],


       [[[4, 6, 1, 1, 9],
         [4, 3, 9, 6, 7],
         [7, 6, 7, 2, 5],
         [9, 7, 9, 4, 8],
         [9, 4, 4, 1, 7]],

        [[5, 7, 1, 9, 1],
         [2, 7, 1, 4, 2],
         [1, 7, 9, 5

In [15]:
val = np.random.randint(1,11)

In [16]:
val 

3

In [19]:
np.eye(4,4)
    
    

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])