In [1]:
 #Concat
 x = [2,3,4]
 y = [5,6,1]

In [2]:
x + y

[2, 3, 4, 5, 6, 1]

In [5]:
import numpy as np

In [6]:
# Numpy array operation
a = np.array(x)
b = np.array(y)


In [7]:
a + b 

array([7, 9, 5])

In [8]:
x * y 

<class 'TypeError'>: can't multiply sequence by non-int of type 'list'

In [9]:
a * b 

array([10, 18,  4])

In [11]:
x * 3

[2, 3, 4, 2, 3, 4, 2, 3, 4]

In [12]:
y * 3


[5, 6, 1, 5, 6, 1, 5, 6, 1]

In [13]:
a * 3

array([ 6,  9, 12])

In [14]:
b * 3

array([15, 18,  3])

In [15]:
# Numpy array attribute

In [17]:
x = np.zeros((2,3))

In [19]:
y = np.zeros((2,5,4))

In [20]:
x.shape # kaç kaçlık olduğuna erişmekteyiz

(2, 3)

In [21]:
y.shape 

(2, 5, 4)

In [22]:
x.ndim

2

In [23]:
y.ndim

3

In [24]:
#kaç elemanlı olduğu
x.size 

6

In [25]:
y.size 

40

In [26]:
x.dtype

dtype('float64')

In [27]:
y.dtype

dtype('float64')