In [1]:
import numpy as np

In [8]:
#Stack
a = np.array([1,2,3,5])
b = np.array([6,7,8,9])

In [4]:
a.shape # row ce column mantığı yok sadece 4 elemanlı bir sayı öbeği

(4,)

In [9]:
np.stack([a,b])

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [10]:
np.stack([a,b], axis = 1)

array([[1, 6],
       [2, 7],
       [3, 8],
       [5, 9]])

In [16]:
np.stack([a,b], axis = 1).shape

(4, 2)

In [18]:
#Splitting
l = [10,20,30,40,50,60,70,80]

In [19]:
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [20]:
a = np.array([10,20,30,40,50,60,70,80])

In [21]:
np.split(a,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [22]:
x,y,z = np.split(a,[2,6])

In [23]:
x

array([10, 20])

In [24]:
y

array([30, 40, 50, 60])

In [25]:
z

array([70, 80])

In [26]:
r,*y = np.split(a,[2,6])

In [27]:
r

array([10, 20])

In [28]:
y

[array([30, 40, 50, 60]), array([70, 80])]

In [29]:
#vsplit
k = np.arange(20).reshape(2,10)

In [30]:
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
np.vsplit(k,[1]) # 1. indeksten böl demek anlamındır. Hepsinin toplamıda python listesidir

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [34]:
np.vsplit(k,[1])[0] # 0. indeksi elemanı getir demektir

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
#HSplit
k = np.arange(20).reshape(2,10)

In [36]:
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [37]:
np.hsplit(k,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [38]:
np.hsplit(k,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [39]:
np.hsplit(k,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
np.hsplit(k,[2])[1].shape

(2, 8)

In [41]:
np.hsplit(k,[2])[0].shape

(2, 2)

In [42]:
x,y = np.hsplit(k,[2])

In [43]:
x

array([[ 0,  1],
       [10, 11]])

In [44]:
y

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [47]:
np.hsplit(k,[2,4])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5,  6,  7,  8,  9],
        [14, 15, 16, 17, 18, 19]])]

In [48]:
a = np.arange(20).reshape(2,10)

In [49]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [51]:
a = np.arange(20).reshape(5,4)

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]